### ISSUE TITLE
The reward on the Test dataset is not as expected

### ISSUE THREAD

**Issue by cycao77** [megvii-research/NeurIPS2021-ML4CO-KIDA#2]
hi, zixuan, I trained the model using your codes on "Item Placement", and evaluated the rewards of 10, 20, 30, 40, 50 iterations and choose models that have top-3 rewards. But the reward on the test dataset is only 4400, I wonder if there are any other tricks I haven't added.  Also, I found that the seed is not set in the script, does this affect the final result?

`python generate_data.py item_placement --file_count ${i} --njobs 5 --train_size 10000 --valid_size 4000`

**Comment by caozixuan** [comment]
Sorry, this problem does exist. We are checking whether the code used in the competition is completely consistent with the code released. We will solve this problem and update the code as soon as possible.

**Comment by caozixuan** [comment]
There was a bug in the code we submitted earlier.  The fix can be seen in https://github.com/megvii-research/NeurIPS2021-ML4CO-KIDA/commit/c79d711ff5c87575305c0cb4dea8dab84ff8f730 . The bug makes one training process only use the data generated in current process. In every iteration process, we should use all the data collected in previous iterations.

We are running the modified code, and we will inform you if the result meets the expectation.

Thank you for your reminder. We are sorry for this bug.

**Comment by caozixuan** [comment]
@cycao77 We ran the modified code again. We tested and averaged the parameters of the model with 20, 30 and 40 rounds of iterations. Finally, the average reward reached 7163.7.

**Comment by cycao77** [comment]
Thank you for your reply.  I'll try again!

**Comment by cycao77** [comment]
epoch_valid_files = rng.choice(
            valid_files,
            int(np.floor(TRAIN_NUM / BATCH_SIZE)) * BATCH_SIZE,
            replace=True,
        )

hi, zhixuan, I wonder if it should be VALID_NUM instead of TRAIN_NUM here ？

**Comment by caozixuan** [comment]
Yes, VALID_NUM should be used here.
